# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/v1/events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='events/v1/events.proto',
  package='fm.events.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x16\x65vents/v1/events.proto\x12\x0c\x66m.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n\nPlayerPlay\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07queueId\x18\x02 \x01(\t\x12\x10\n\x08provider\x18\x03 \x01(\t\x12\x0f\n\x07trackId\x18\x04 \x01(\t\x12\x0e\n\x06userId\x18\x05 \x01(\tB4Z2github.com/thisissoon-fm/proto.go/events/v1;eventsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PLAYERPLAY = _descriptor.Descriptor(
  name='PlayerPlay',
  full_name='fm.events.v1.PlayerPlay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='fm.events.v1.PlayerPlay.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queueId', full_name='fm.events.v1.PlayerPlay.queueId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provider', full_name='fm.events.v1.PlayerPlay.provider', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackId', full_name='fm.events.v1.PlayerPlay.trackId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='fm.events.v1.PlayerPlay.userId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=200,
)

_PLAYERPLAY.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PlayerPlay'] = _PLAYERPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerPlay = _reflection.GeneratedProtocolMessageType('PlayerPlay', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERPLAY,
  __module__ = 'events.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:fm.events.v1.PlayerPlay)
  ))
_sym_db.RegisterMessage(PlayerPlay)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z2github.com/thisissoon-fm/proto.go/events/v1;events'))
# @@protoc_insertion_point(module_scope)
