# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue/v1/manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from providers.v1 import providers_pb2 as providers_dot_v1_dot_providers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='queue/v1/manager.proto',
  package='fm.queue.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x16queue/v1/manager.proto\x12\x0b\x66m.queue.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cproviders/v1/providers.proto\"Z\n\nPutRequest\x12+\n\x08provider\x18\x01 \x01(\x0e\x32\x19.fm.providers.v1.Provider\x12\x0f\n\x07trackId\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\t\"9\n\x0bPutResponse\x12*\n\tqueueItem\x18\x01 \x01(\x0b\x32\x17.fm.queue.v1.QueueTrack\"9\n\x0bPopResponse\x12*\n\tqueueItem\x18\x01 \x01(\x0b\x32\x17.fm.queue.v1.QueueTrack\":\n\x0cNextResponse\x12*\n\tqueueItem\x18\x01 \x01(\x0b\x32\x17.fm.queue.v1.QueueTrack\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"-\n\x0cQueueRequest\x12\r\n\x05limit\x18\x01 \x01(\x03\x12\x0e\n\x06offset\x18\x02 \x01(\x03\"f\n\nQueueTrack\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x07\x63reated\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07trackId\x18\x03 \x01(\t\x12\x0e\n\x06userId\x18\x04 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t2\x82\x03\n\x0cQueueManager\x12:\n\x03Put\x12\x17.fm.queue.v1.PutRequest\x1a\x18.fm.queue.v1.PutResponse\"\x00\x12;\n\x04Next\x12\x16.google.protobuf.Empty\x1a\x19.fm.queue.v1.NextResponse\"\x00\x12\x39\n\x03Pop\x12\x16.google.protobuf.Empty\x1a\x18.fm.queue.v1.PopResponse\"\x00\x12=\n\x05\x43ount\x12\x16.google.protobuf.Empty\x1a\x1a.fm.queue.v1.CountResponse\"\x00\x12?\n\x05Queue\x12\x19.fm.queue.v1.QueueRequest\x1a\x17.fm.queue.v1.QueueTrack\"\x00\x30\x01\x12>\n\x06\x44\x65lete\x12\x1a.fm.queue.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x00\x42\x32Z0github.com/thisissoon-fm/proto.go/queue/v1;queueb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,providers_dot_v1_dot_providers__pb2.DESCRIPTOR,])




_PUTREQUEST = _descriptor.Descriptor(
  name='PutRequest',
  full_name='fm.queue.v1.PutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider', full_name='fm.queue.v1.PutRequest.provider', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackId', full_name='fm.queue.v1.PutRequest.trackId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='fm.queue.v1.PutRequest.userId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=221,
)


_PUTRESPONSE = _descriptor.Descriptor(
  name='PutResponse',
  full_name='fm.queue.v1.PutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queueItem', full_name='fm.queue.v1.PutResponse.queueItem', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=280,
)


_POPRESPONSE = _descriptor.Descriptor(
  name='PopResponse',
  full_name='fm.queue.v1.PopResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queueItem', full_name='fm.queue.v1.PopResponse.queueItem', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=339,
)


_NEXTRESPONSE = _descriptor.Descriptor(
  name='NextResponse',
  full_name='fm.queue.v1.NextResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queueItem', full_name='fm.queue.v1.NextResponse.queueItem', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=399,
)


_COUNTRESPONSE = _descriptor.Descriptor(
  name='CountResponse',
  full_name='fm.queue.v1.CountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='fm.queue.v1.CountResponse.count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=431,
)


_QUEUEREQUEST = _descriptor.Descriptor(
  name='QueueRequest',
  full_name='fm.queue.v1.QueueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='fm.queue.v1.QueueRequest.limit', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='fm.queue.v1.QueueRequest.offset', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=478,
)


_QUEUETRACK = _descriptor.Descriptor(
  name='QueueTrack',
  full_name='fm.queue.v1.QueueTrack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fm.queue.v1.QueueTrack.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='fm.queue.v1.QueueTrack.created', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackId', full_name='fm.queue.v1.QueueTrack.trackId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userId', full_name='fm.queue.v1.QueueTrack.userId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=582,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='fm.queue.v1.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fm.queue.v1.DeleteRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=611,
)

_PUTREQUEST.fields_by_name['provider'].enum_type = providers_dot_v1_dot_providers__pb2._PROVIDER
_PUTRESPONSE.fields_by_name['queueItem'].message_type = _QUEUETRACK
_POPRESPONSE.fields_by_name['queueItem'].message_type = _QUEUETRACK
_NEXTRESPONSE.fields_by_name['queueItem'].message_type = _QUEUETRACK
_QUEUETRACK.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PutRequest'] = _PUTREQUEST
DESCRIPTOR.message_types_by_name['PutResponse'] = _PUTRESPONSE
DESCRIPTOR.message_types_by_name['PopResponse'] = _POPRESPONSE
DESCRIPTOR.message_types_by_name['NextResponse'] = _NEXTRESPONSE
DESCRIPTOR.message_types_by_name['CountResponse'] = _COUNTRESPONSE
DESCRIPTOR.message_types_by_name['QueueRequest'] = _QUEUEREQUEST
DESCRIPTOR.message_types_by_name['QueueTrack'] = _QUEUETRACK
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PutRequest = _reflection.GeneratedProtocolMessageType('PutRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTREQUEST,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.PutRequest)
  ))
_sym_db.RegisterMessage(PutRequest)

PutResponse = _reflection.GeneratedProtocolMessageType('PutResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTRESPONSE,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.PutResponse)
  ))
_sym_db.RegisterMessage(PutResponse)

PopResponse = _reflection.GeneratedProtocolMessageType('PopResponse', (_message.Message,), dict(
  DESCRIPTOR = _POPRESPONSE,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.PopResponse)
  ))
_sym_db.RegisterMessage(PopResponse)

NextResponse = _reflection.GeneratedProtocolMessageType('NextResponse', (_message.Message,), dict(
  DESCRIPTOR = _NEXTRESPONSE,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.NextResponse)
  ))
_sym_db.RegisterMessage(NextResponse)

CountResponse = _reflection.GeneratedProtocolMessageType('CountResponse', (_message.Message,), dict(
  DESCRIPTOR = _COUNTRESPONSE,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.CountResponse)
  ))
_sym_db.RegisterMessage(CountResponse)

QueueRequest = _reflection.GeneratedProtocolMessageType('QueueRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUEUEREQUEST,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.QueueRequest)
  ))
_sym_db.RegisterMessage(QueueRequest)

QueueTrack = _reflection.GeneratedProtocolMessageType('QueueTrack', (_message.Message,), dict(
  DESCRIPTOR = _QUEUETRACK,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.QueueTrack)
  ))
_sym_db.RegisterMessage(QueueTrack)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEREQUEST,
  __module__ = 'queue.v1.manager_pb2'
  # @@protoc_insertion_point(class_scope:fm.queue.v1.DeleteRequest)
  ))
_sym_db.RegisterMessage(DeleteRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z0github.com/thisissoon-fm/proto.go/queue/v1;queue'))

_QUEUEMANAGER = _descriptor.ServiceDescriptor(
  name='QueueManager',
  full_name='fm.queue.v1.QueueManager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=614,
  serialized_end=1000,
  methods=[
  _descriptor.MethodDescriptor(
    name='Put',
    full_name='fm.queue.v1.QueueManager.Put',
    index=0,
    containing_service=None,
    input_type=_PUTREQUEST,
    output_type=_PUTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Next',
    full_name='fm.queue.v1.QueueManager.Next',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_NEXTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Pop',
    full_name='fm.queue.v1.QueueManager.Pop',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_POPRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Count',
    full_name='fm.queue.v1.QueueManager.Count',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_COUNTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Queue',
    full_name='fm.queue.v1.QueueManager.Queue',
    index=4,
    containing_service=None,
    input_type=_QUEUEREQUEST,
    output_type=_QUEUETRACK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='fm.queue.v1.QueueManager.Delete',
    index=5,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUEUEMANAGER)

DESCRIPTOR.services_by_name['QueueManager'] = _QUEUEMANAGER

# @@protoc_insertion_point(module_scope)
