# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from queue.v1 import manager_pb2 as queue_dot_v1_dot_manager__pb2


class QueueManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Put = channel.unary_unary(
        '/fm.queue.v1.QueueManager/Put',
        request_serializer=queue_dot_v1_dot_manager__pb2.PutRequest.SerializeToString,
        response_deserializer=queue_dot_v1_dot_manager__pb2.PutResponse.FromString,
        )
    self.Next = channel.unary_unary(
        '/fm.queue.v1.QueueManager/Next',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=queue_dot_v1_dot_manager__pb2.NextResponse.FromString,
        )
    self.Pop = channel.unary_unary(
        '/fm.queue.v1.QueueManager/Pop',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=queue_dot_v1_dot_manager__pb2.PopResponse.FromString,
        )
    self.Count = channel.unary_unary(
        '/fm.queue.v1.QueueManager/Count',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=queue_dot_v1_dot_manager__pb2.CountResponse.FromString,
        )
    self.Queue = channel.unary_stream(
        '/fm.queue.v1.QueueManager/Queue',
        request_serializer=queue_dot_v1_dot_manager__pb2.QueueRequest.SerializeToString,
        response_deserializer=queue_dot_v1_dot_manager__pb2.QueueItem.FromString,
        )
    self.Delete = channel.unary_unary(
        '/fm.queue.v1.QueueManager/Delete',
        request_serializer=queue_dot_v1_dot_manager__pb2.DeleteRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class QueueManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Put(self, request, context):
    """Put adds a new track to the queue
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Next(self, request, context):
    """Next returns the next track in the queue
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Pop(self, request, context):
    """Pop takes the first item in the queue, removing it
    from the queue and returning it
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Count(self, request, context):
    """Count returns the totoal number of items in the queue
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Queue(self, request, context):
    """Queue returns the current queue as a stream of queue items
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Delete removes a specific item from the queue
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QueueManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=queue_dot_v1_dot_manager__pb2.PutRequest.FromString,
          response_serializer=queue_dot_v1_dot_manager__pb2.PutResponse.SerializeToString,
      ),
      'Next': grpc.unary_unary_rpc_method_handler(
          servicer.Next,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=queue_dot_v1_dot_manager__pb2.NextResponse.SerializeToString,
      ),
      'Pop': grpc.unary_unary_rpc_method_handler(
          servicer.Pop,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=queue_dot_v1_dot_manager__pb2.PopResponse.SerializeToString,
      ),
      'Count': grpc.unary_unary_rpc_method_handler(
          servicer.Count,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=queue_dot_v1_dot_manager__pb2.CountResponse.SerializeToString,
      ),
      'Queue': grpc.unary_stream_rpc_method_handler(
          servicer.Queue,
          request_deserializer=queue_dot_v1_dot_manager__pb2.QueueRequest.FromString,
          response_serializer=queue_dot_v1_dot_manager__pb2.QueueItem.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=queue_dot_v1_dot_manager__pb2.DeleteRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'fm.queue.v1.QueueManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
