# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: providers/v1/providers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='providers/v1/providers.proto',
  package='fm.providers.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x1cproviders/v1/providers.proto\x12\x0f\x66m.providers.v1*7\n\x08Provider\x12\x0b\n\x07Spotify\x10\x00\x12\x0e\n\nGooglePlay\x10\x01\x12\x0e\n\nSoundCloud\x10\x02\x42:Z8github.com/thisissoon-fm/proto.go/providers/v1;providersb\x06proto3')
)

_PROVIDER = _descriptor.EnumDescriptor(
  name='Provider',
  full_name='fm.providers.v1.Provider',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Spotify', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GooglePlay', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SoundCloud', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=49,
  serialized_end=104,
)
_sym_db.RegisterEnumDescriptor(_PROVIDER)

Provider = enum_type_wrapper.EnumTypeWrapper(_PROVIDER)
Spotify = 0
GooglePlay = 1
SoundCloud = 2


DESCRIPTOR.enum_types_by_name['Provider'] = _PROVIDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z8github.com/thisissoon-fm/proto.go/providers/v1;providers'))
# @@protoc_insertion_point(module_scope)
